### ISSUE TITLE
DGLError when running GINN

### ISSUE THREAD

**Issue by thongjlj** [spindro/GINN#2]
Hi Indro,

I'm facing this issue when trying to run the example notebook:

DGLError: DGLGraph.from_networkx is deprecated. Please call the following

	 dgl.from_networkx(nx_graph, node_attrs, edge_attrs)

, which creates a new DGLGraph from the networkx graph.

May I know if there is any way to fix this?

**Comment by spindro** [comment]
Hi!

The easiest way to fix-it is to roll back DGL to a previous version.
Alternatively, you can replace the call as suggested by DGL.

**Comment by thongjlj** [comment]
I rolled back DGL to version 0.3 and it worked fine. Thank you!
